l=int(input("Enter the Length of rectangle: "))
b=int(input("Enter the Breadth of rectangle: "))
file=open("area_perimeter_rectangle.txt",'w')
file.write("Enter the Length of rectangle: ")
file.write(str(l))
file.write('\n')
file.write("Enter the Breadth of rectangle: ")
file.write(str(b))
file.write('\n')
Area=l*b
Perimeter=2*(l+b)
print("Area of a Rectangle is,",Area)
print("Perimeter of a Rectangle is,",Perimeter)
file.write("Area of a Rectangle is,")
file.write(str(Area))
file.write('\n')
file.write("Perimeter of a Rectangle is,")
file.write(str(Perimeter))